name: Check dev

on:
  push:
    branches: ['dev']
    paths-ignore:
      - 'README.md'
      - '**/LICENSE'
      - '**/.editorconfig'
      - '**/.vscode/**'
  pull_request:
    branches: ['master', 'dev']
    paths-ignore:
      - 'README.md'
      - '**/LICENSE'
      - '**/.editorconfig'
      - '**/.vscode/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build
        uses: ./.github/actions/build
        env:
          NODE_ENV: production
          PUBLIC_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          TURNSTILE_SECRET_KEY: ${{ secrets.TURNSTILE_SECRET_KEY }}
          PUBLIC_TURNSTILE_SITE_KEY: ${{ secrets.TURNSTILE_SITE_KEY }}

      - name: Run checks
        run: npm run check

      - name: Run tests
        run: npm run test:ci
